name: Build Final Pine Script

on:
  push:
    paths:
      - 'Libraries/**.pine'
      - 'Strategies/**.pine'
      - 'build.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run build script
        run: python build.py

      - name: Commit and push updated final_strategy.pine
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add final_strategy.pine
          git commit -m "🤖 Auto-build final strategy on push" || echo "No changes to commit"
          git push
